Repository booklore-app/booklore, pull requests merged in 2025-04, with the labels that each got.

#66 Add missing mariadb creds
  README.md
Labels: documentation

#69 Extract and set the series name and index for EPUBs
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java
Labels: bug

#72 Display full file path in metadata viewer
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/Book.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BooksService.java
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.html
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: feature

#82 Automatically delete all remote branches that have been merged into m…
  .github/workflows/docker-build-publish.yml
Labels: ci

#80 Implement cover size selection and regeneration
  booklore-api/src/main/java/com/adityachandel/booklore/controller/AppSettingController.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MetadataController.java
  booklore-api/src/main/java/com/adityachandel/booklore/exception/ApiError.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/SettingRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/AppSettingEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/AppSettingsRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BooksService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/FileProcessingUtils.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/PdfProcessor.java
  booklore-api/src/main/resources/db/migration/V4__Insert_Cover_Image_Settings.sql
  booklore-ui/src/app/app.component.ts
  booklore-ui/src/app/book/components/pdf-viewer/pdf-viewer.component.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/core/component/settings/metadata-settings/metadata-settings.component.ts
  booklore-ui/src/app/core/component/settings/settings.component.html
  booklore-ui/src/app/core/component/settings/settings.component.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/core/service/app-settings.service.ts
  booklore-ui/src/app/global-preferences/global-preferences.component.html
  booklore-ui/src/app/global-preferences/global-preferences.component.scss
  booklore-ui/src/app/global-preferences/global-preferences.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
Labels: feature

#83 Initialize entityOptions based on runtime entity type (Library or Shelf)
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
Labels: bug

#85 Fix unshelf button not working
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
Labels: bug

#89 Fix metadata setting not getting saved
  booklore-api/src/main/java/com/adityachandel/booklore/controller/AppSettingController.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
Labels: bug

#94 Watch only for create and delete events in folder watcher
  booklore-api/src/main/java/com/adityachandel/booklore/service/monitoring/MonitoringTask.java
Labels: bug

#100 Include author name in the goodreads search term
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
Labels: bug

#96 Build image for all branches
  .github/workflows/docker-build-publish.yml
Labels: ci

#101 Fix white-on-white text issue by setting darkModeSelector for PrimeNG
  booklore-ui/src/main.ts
Labels: bug

#107 Hide progress-bar for the uploader & Make "uploading" icon spin
  booklore-ui/src/app/utilities/component/book-uploader/book-uploader.component.html
  booklore-ui/src/app/utilities/component/book-uploader/book-uploader.component.scss
Labels: enhancement

#110 Resolve issue with email being sent to wrong recipient
  booklore-api/src/main/java/com/adityachandel/booklore/repository/EmailRecipientRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/EmailService.java
Labels: bug

#112 Tweak layout and spacing on metadata details page
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
Labels: enhancement

#115 Make genre tags horizontally scrollable
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
Labels: enhancement

#117 Implement version info endpoint and update version display in UI
  .github/workflows/docker-build-publish.yml
  Dockerfile
  booklore-api/src/main/java/com/adityachandel/booklore/controller/VersionController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/VersionInfo.java
  booklore-api/src/main/resources/application.yaml
  booklore-ui/src/app/core/service/version.service.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.html
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.ts
  booklore-ui/src/environments/version.ts
Labels: enhancement

#120 Add Reset Button for Metadata Fields in Metadata Picker Tab
  booklore-ui/src/app/metadata/book-metadata-center/metadata-picker/metadata-picker.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-picker/metadata-picker.component.scss
  booklore-ui/src/app/metadata/book-metadata-center/metadata-picker/metadata-picker.component.ts
Labels: enhancement

#123 Add bulk lock/unlock metadata functionality for books
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MetadataController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/ToggleAllLockRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookMetadataEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/enums/Lock.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataService.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.scss
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/book-browser/lock-unlock-metadata-dialog/lock-unlock-metadata-dialog.component.html
  booklore-ui/src/app/book/components/book-browser/lock-unlock-metadata-dialog/lock-unlock-metadata-dialog.component.scss
  booklore-ui/src/app/book/components/book-browser/lock-unlock-metadata-dialog/lock-unlock-metadata-dialog.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: enhancement

#128 Separate ratings for Amazon and Goodreads
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookMetadataEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-api/src/main/resources/db/migration/V6__Add_amazon_goodreads_rating_columns.sql
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: feature

#130 Support automatic version bump using PR labels or commit messages
  .github/workflows/docker-build-publish.yml
Labels: ci, patch

#134 Display changelog from current version to latest upon clicking the update link
  booklore-api/src/main/java/com/adityachandel/booklore/controller/VersionController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/ReleaseNote.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/VersionInfo.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/VersionService.java
  booklore-api/src/main/resources/application.yaml
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/core/service/version.service.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.html
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.ts
  booklore-ui/src/app/layout/component/layout-menu/version-changelog-dialog/version-changelog-dialog.component.html
  booklore-ui/src/app/layout/component/layout-menu/version-changelog-dialog/version-changelog-dialog.component.scss
  booklore-ui/src/app/layout/component/layout-menu/version-changelog-dialog/version-changelog-dialog.component.ts
  booklore-ui/src/main.ts
  booklore-ui/tailwind.config.js
Labels: enhancement, patch

#136 fix: use correct server port for dev server
  booklore-ui/angular.json
  booklore-ui/package.json
  booklore-ui/src/environments/environment.ts
Labels: enhancement, patch

#138 fix: uploading books on Windows (dev env) doesn't work
  booklore-api/src/main/java/com/adityachandel/booklore/config/AppProperties.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/FileUploadService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/FileProcessingUtils.java
  booklore-api/src/main/resources/application.yaml
Labels: bug, patch

#145 Implement similar books recommendation services
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookRecommendation.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookRecommendationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookSimilarityService.java
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: feature, minor

#146 Transition book metadata center from dynamic dialog to routed view
  booklore-ui/src/app/app.routes.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/book-searcher/book-searcher.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.html
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.service.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-picker/metadata-picker.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/metadata/service/metadata-dialog.service.ts
Labels: enhancement

#148 Integrate Similar Book Recommendations in Book Metadata Center UI
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.service.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: feature, minor

#151 Display other books from the same series on the metadata viewer page
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookRecommendationService.java
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: feature, minor

#152 Add toggle to enable/disable book recommendations
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
  booklore-ui/src/app/settings/settings.component.html
  booklore-ui/src/app/settings/settings.component.ts
Labels: enhancement, minor

#153 Fix similar books not getting updated
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.html
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: bug

#155 Move book similarity recommendation logic to scheduled background job
  booklore-api/src/main/java/com/adityachandel/booklore/BookloreApplication.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-api/src/main/java/com/adityachandel/booklore/convertor/BookRecommendationIdsListConverter.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/BookMapper.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookRecommendation.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookRecommendationLite.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/recommender/BookRecommendationScheduler.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/recommender/BookRecommendationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/recommender/BookSimilarityService.java
  booklore-api/src/main/resources/db/migration/V7__Add_similar_books_json_column_to_book.sql
Labels: enhancement, minor

#163 Merge Develop into Master - Release v0.2.1
  booklore-ui/src/app/custom-reuse-strategy.ts
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.service.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.ts
Labels: patch

#166 Add ‘Other’ and ‘Refactoring’, and categories to drafter template
  .github/release-drafter.yml
Labels: documentation

#168 Remove allFieldsLocked field
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookMetadataEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataUpdater.java
Labels: maintenance

#169 Add more sort options
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/sort.service.ts
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.ts
Labels: enhancement, minor

#172 Add more columns to table view
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
Labels: enhancement, minor

#176 Sync filter sidebar state with URL parameter
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
Labels: enhancement, minor

#178 Metadata viewer small UI changes
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
Labels: maintenance

#180 Stop current metadata request when book changes
  booklore-ui/src/app/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.ts
Labels: bug

#181 Suppress repetitive WebSocket & Hikari connection validation logs
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/WebSocketAuthInterceptor.java
  booklore-api/src/main/resources/application.yaml
Labels: patch, cleanup

#207 Enable quill in metadata editor and viewer
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: enhancement

#210 Support configurable file/folder naming pattern for uploaded files
  booklore-api/src/main/java/com/adityachandel/booklore/config/BeanConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/JwtUtils.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/FileUploadController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/UploadedFileMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookFileMetadataExtractor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/EpubMetadataExtractor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/FileUploadService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/PdfMetadataExtractor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/FileProcessingUtils.java
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/file-upload-pattern/file-upload-pattern.component.html
  booklore-ui/src/app/file-upload-pattern/file-upload-pattern.component.scss
  booklore-ui/src/app/file-upload-pattern/file-upload-pattern.component.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
  booklore-ui/src/styles.scss
Labels: feature, minor

#212 Merge Develop into Master for Release v0.4.0
  .github/release-drafter.yml
  Dockerfile
  README.md
  booklore-api/src/main/java/com/adityachandel/booklore/config/AppProperties.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/BeanConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/AuthenticationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/JwtUtils.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/AuthenticationController.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/FileUploadController.java
  booklore-api/src/main/java/com/adityachandel/booklore/exception/ApiError.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/UploadedFileMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookFileMetadataExtractor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/EpubMetadataExtractor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/FileUploadService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/PdfMetadataExtractor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/FileProcessingUtils.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserCreatorService.java
  booklore-api/src/main/resources/application.yaml
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/core/component/login/login.component.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/core/service/auth.service.ts
  booklore-ui/src/app/file-upload-pattern/file-upload-pattern.component.html
  booklore-ui/src/app/file-upload-pattern/file-upload-pattern.component.scss
  booklore-ui/src/app/file-upload-pattern/file-upload-pattern.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
  booklore-ui/src/styles.scss
Labels: minor

#215 Display the file size in the book metadata details section
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/Book.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/LibraryFile.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/AppMigrationEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/AppMigrationRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/BookRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppMigrationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppMigrationStartup.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookCreatorService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BooksService.java
  booklore-api/src/main/java/com/adityachandel/booklore/util/FileUtils.java
  booklore-api/src/main/resources/db/migration/V8__Add_file_size_column_to_book_table.sql
  booklore-api/src/main/resources/db/migration/V9__Create_app_migration_table.sql
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: feature

#219 Apply color palette to rating stars in book metadata viewer
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: enhancement

#235 Implement OPDS server
  booklore-api/src/main/java/com/adityachandel/booklore/config/WebMvcConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/CustomOpdsUserDetailsService.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/OpdsController.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/OpdsUserController.java
  booklore-api/src/main/java/com/adityachandel/booklore/interceptor/OpdsEnabledInterceptor.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/OpdsUserMapper.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/OpdsUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/OpdsUserCreateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/PasswordResetRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/OpdsUserEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/OpdsUserRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/OpdsService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/OpdsUserService.java
  booklore-api/src/main/resources/db/migration/V10__Create_opds_user_table.sql
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/file-upload-pattern/file-upload-pattern.component.html
  booklore-ui/src/app/file-upload-pattern/file-upload-pattern.component.ts
  booklore-ui/src/app/opds-settings/opds-settings.component.html
  booklore-ui/src/app/opds-settings/opds-settings.component.scss
  booklore-ui/src/app/opds-settings/opds-settings.component.ts
  booklore-ui/src/app/opds-user.service.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
Labels: feature

#236 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/config/WebMvcConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/CustomOpdsUserDetailsService.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/WebSocketAuthInterceptor.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/OpdsController.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/OpdsUserController.java
  booklore-api/src/main/java/com/adityachandel/booklore/interceptor/OpdsEnabledInterceptor.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/OpdsUserMapper.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/Book.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/OpdsUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/OpdsUserCreateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/PasswordResetRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/LibraryFile.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/AppMigrationEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/OpdsUserEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/AppMigrationRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/BookRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/OpdsUserRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppMigrationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppMigrationStartup.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookCreatorService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BooksService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/OpdsService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/OpdsUserService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserService.java
  booklore-api/src/main/java/com/adityachandel/booklore/util/FileUtils.java
  booklore-api/src/main/resources/db/migration/V10__Create_opds_user_table.sql
  booklore-api/src/main/resources/db/migration/V8__Add_file_size_column_to_book_table.sql
  booklore-api/src/main/resources/db/migration/V9__Create_app_migration_table.sql
  booklore-ui/src/app/app.routes.ts
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/pdf-viewer/pdf-viewer.component.html
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/sort.service.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/file-upload-pattern/file-upload-pattern.component.html
  booklore-ui/src/app/file-upload-pattern/file-upload-pattern.component.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/opds-settings/opds-settings.component.html
  booklore-ui/src/app/opds-settings/opds-settings.component.scss
  booklore-ui/src/app/opds-settings/opds-settings.component.ts
  booklore-ui/src/app/opds-user.service.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
  booklore-ui/src/app/user-profile-dialog/user-profile-dialog.component.html
  booklore-ui/src/app/user-profile-dialog/user-profile-dialog.component.scss
  booklore-ui/src/app/user-profile-dialog/user-profile-dialog.component.ts
  booklore-ui/src/app/user.service.ts
Labels: documentation

#238 Display OPDS Server Endpoint in the Application UI
  booklore-ui/src/app/opds-settings/opds-settings.component.html
  booklore-ui/src/app/opds-settings/opds-settings.component.ts
Labels: enhancement, patch

#239 Merge Develop into Master for Release
  booklore-ui/src/app/opds-settings/opds-settings.component.html
  booklore-ui/src/app/opds-settings/opds-settings.component.ts
Labels: documentation

#241 Refactor settings page: standardize styling and reorganize components
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
  booklore-ui/src/app/book/components/pdf-viewer/pdf-viewer.component.ts
  booklore-ui/src/app/core/component/change-password/change-password.component.ts
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.html
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.html
  booklore-ui/src/app/settings/admin/create-user-dialog/create-user-dialog.component.scss
  booklore-ui/src/app/settings/book-preferences/book-preferences.component.ts
  booklore-ui/src/app/settings/email/email-provider/email-provider.component.html
  booklore-ui/src/app/settings/email/email-recipient/email-recipient.component.html
  booklore-ui/src/app/settings/global-preferences/file-upload-pattern/file-upload-pattern.component.html
  booklore-ui/src/app/settings/global-preferences/file-upload-pattern/file-upload-pattern.component.scss
  booklore-ui/src/app/settings/global-preferences/file-upload-pattern/file-upload-pattern.component.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-settings.component.html
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-settings.component.scss
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-settings.component.ts
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-user.service.ts
  booklore-ui/src/app/settings/global-preferences/user-profile-dialog/user-profile-dialog.component.html
  booklore-ui/src/app/settings/global-preferences/user-profile-dialog/user-profile-dialog.component.scss
  booklore-ui/src/app/settings/global-preferences/user-profile-dialog/user-profile-dialog.component.ts
  booklore-ui/src/app/settings/settings.component.html
  booklore-ui/src/app/settings/settings.component.ts
  booklore-ui/src/app/settings/user-management/create-user-dialog/create-user-dialog.component.html
  booklore-ui/src/app/settings/user-management/create-user-dialog/create-user-dialog.component.scss
  booklore-ui/src/app/settings/user-management/create-user-dialog/create-user-dialog.component.ts
  booklore-ui/src/app/settings/user-management/user-management.component.html
  booklore-ui/src/app/settings/user-management/user-management.component.scss
  booklore-ui/src/app/settings/user-management/user-management.component.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
Labels: patch, cleanup

#244 Implement Secure Refresh Token Rotation with Revocation Support
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/AuthenticationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/JwtUtils.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/RefreshTokenEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/RefreshTokenRepository.java
  booklore-api/src/main/resources/db/migration/V11__Create_refresh_token_table.sql
Labels: minor
