Repository booklore-app/booklore, pull requests merged in 2025-09, with the labels that each got.

#1064 Add "OPDS Server Enabled" button to OPDS v2 settings
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/settings/device-settings-component/koreader-settings-component/koreader-settings-component.scss
  booklore-ui/src/app/settings/opds-settings-v2/opds-settings-v2.html
  booklore-ui/src/app/settings/opds-settings-v2/opds-settings-v2.scss
  booklore-ui/src/app/settings/opds-settings-v2/opds-settings-v2.ts
  booklore-ui/src/app/settings/opds-settings/opds-settings.component.html
  booklore-ui/src/app/settings/opds-settings/opds-settings.component.scss
  booklore-ui/src/app/settings/settings.component.html
Labels: chore

#1065 Merge develop into master for the release
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/pdf-viewer/pdf-viewer.component.html
  booklore-ui/src/app/book/components/pdf-viewer/pdf-viewer.component.ts
  booklore-ui/src/app/bookdrop/bookdrop-file-review-component/bookdrop-file-review.component.html
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-picker/metadata-picker.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/settings/device-settings-component/koreader-settings-component/koreader-settings-component.scss
  booklore-ui/src/app/settings/opds-settings-v2/opds-settings-v2.html
  booklore-ui/src/app/settings/opds-settings-v2/opds-settings-v2.scss
  booklore-ui/src/app/settings/opds-settings-v2/opds-settings-v2.ts
  booklore-ui/src/app/settings/opds-settings/opds-settings.component.html
  booklore-ui/src/app/settings/opds-settings/opds-settings.component.scss
  booklore-ui/src/app/settings/settings.component.html
Labels: patch, skip changelog

#1089 Implement comprehensive library stats and charts
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-ui/angular.json
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/app.routes.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
  booklore-ui/src/app/metadata/cover-search/cover-search.component.html
  booklore-ui/src/app/stats-component/charts-service/author-popularity-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/author-series-portfolio-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/book-quality-score-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/book-rating-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/book-size-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/book-type-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/chart-config.service.ts
  booklore-ui/src/app/stats-component/charts-service/finished-books-timeline-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/language-distribution-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/libraries-summary.service.ts
  booklore-ui/src/app/stats-component/charts-service/library-filter.service.ts
  booklore-ui/src/app/stats-component/charts-service/monthly-reading-patterns-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/page-count-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/personal-rating-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/publication-year-chart-service.ts
  booklore-ui/src/app/stats-component/charts-service/read-status-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/reading-completion-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/reading-dna-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/reading-habits-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/reading-progress-chart-service.ts
  booklore-ui/src/app/stats-component/charts-service/reading-velocity-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/reading-velocity-timeline-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/series-completion-progress-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/series-length-distribution-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/series-standalone-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/top-categories-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/top-series-chart.service.ts
  booklore-ui/src/app/stats-component/stats-component.html
  booklore-ui/src/app/stats-component/stats-component.scss
  booklore-ui/src/app/stats-component/stats-component.ts
  booklore-ui/src/main.ts
Labels: feature

#1091 Add 'Books Finished per Month' heat map chart
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/stats-component/charts-service/chart-config.service.ts
  booklore-ui/src/app/stats-component/charts-service/finished-books-timeline-chart.service.ts
  booklore-ui/src/app/stats-component/charts-service/reading-heatmap-chart.service.ts
  booklore-ui/src/app/stats-component/finished-books-timeline-chart.service.ts
  booklore-ui/src/app/stats-component/stats-component.html
  booklore-ui/src/app/stats-component/stats-component.scss
  booklore-ui/src/app/stats-component/stats-component.ts
Labels: feature

#882 Adding USER_ID and GROUP_ID to specify permission without making breaking change
  Dockerfile
  README.md
  booklore-api/src/main/java/com/adityachandel/booklore/service/upload/FileUploadService.java
  example-docker/.env
  start.sh
Labels: refactor

#1085 feat: Add comprehensive race condition prevention for file operations
  booklore-api/src/main/java/com/adityachandel/booklore/service/AdditionalFileService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookDropService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/FileMoveService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/monitoring/MonitoringProtectionService.java
  booklore-api/src/test/java/com/adityachandel/booklore/BookServiceDeleteTests.java
  booklore-api/src/test/java/com/adityachandel/booklore/FileMoveServiceMoveFilesTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/AdditionalFileServiceTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/BookServiceDeleteBooksTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/MonitoringProtectionConcurrentTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/MonitoringProtectionIntegrationTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/MonitoringProtectionRaceConditionTest.java
Labels: enhancement

#1102 Fix database lockout caused by duplicate files in library
  booklore-api/src/main/java/com/adityachandel/booklore/model/DuplicateFileInfo.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/FileProcessResult.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/DuplicateFileNotification.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/LibraryFile.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/enums/FileProcessStatus.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/websocket/Topic.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookDropService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/event/BookEventBroadcaster.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/AbstractFileProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/BookFileProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/BookDeletionService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/BookRestorationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/FileAsBookProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/FolderAsBookFileProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryProcessingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/upload/FileUploadService.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/BookServiceDeleteBooksTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/fileprocessor/AbstractFileProcessorTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/library/FileAsBookProcessorTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/library/FolderAsBookFileProcessorTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/upload/FileUploadServiceTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/util/builder/LibraryTestBuilder.java
  booklore-ui/src/app/app.component.ts
  booklore-ui/src/app/core/component/duplicate-files-notification/duplicate-files-dialog.component.html
  booklore-ui/src/app/core/component/duplicate-files-notification/duplicate-files-dialog.component.scss
  booklore-ui/src/app/core/component/duplicate-files-notification/duplicate-files-dialog.component.ts
  booklore-ui/src/app/core/component/duplicate-files-notification/duplicate-files-notification.component.html
  booklore-ui/src/app/core/component/duplicate-files-notification/duplicate-files-notification.component.scss
  booklore-ui/src/app/core/component/duplicate-files-notification/duplicate-files-notification.component.ts
  booklore-ui/src/app/core/component/live-notification-box/live-notification-box.component.scss
  booklore-ui/src/app/core/component/live-task-event-box/live-task-event-box.component.scss
  booklore-ui/src/app/core/component/unified-notification-popover-component/unified-notification-popover-component.html
  booklore-ui/src/app/core/component/unified-notification-popover-component/unified-notification-popover-component.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
  booklore-ui/src/app/shared/websocket/duplicate-file.service.ts
  booklore-ui/src/app/shared/websocket/model/duplicate-file-notification.model.ts
Labels: bug

#1103 Add chart button to mobile layout
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/stats-component/stats-component.html
Labels: chore

#1010 Adding a Helm chart to install in Kubernetes
  .gitignore
  example-chart/Chart.yaml
  example-chart/templates/_helpers.tpl
  example-chart/templates/deployment.yaml
  example-chart/templates/ingress.yaml
  example-chart/templates/pvc.yaml
  example-chart/templates/service.yaml
  example-chart/templates/serviceaccount.yaml
  example-chart/values.yaml
Labels: documentation, ci

#1108 Preserve sidebar filter state in mobile view
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
Labels: bug

#1110 Ensure Magic Shelf correctly evaluates rules with fractional numeric …
  booklore-ui/src/app/book-rule-evaluator.service.ts
Labels: bug

#1111 Fix multi-book review dialog to accurately reflect current state
  booklore-ui/src/app/book/components/book-browser/lock-unlock-metadata-dialog/lock-unlock-metadata-dialog.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-picker/metadata-picker.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/metadata/metadata-review-dialog-component/metadata-review-dialog-component.html
  booklore-ui/src/app/metadata/metadata-review-dialog-component/metadata-review-dialog-component.ts
Labels: bug

#1114 Update docker-compose.yml
  example-docker/docker-compose.yml
Labels: chore

#1146 Automatically detect and set book subtitle from title field
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/MonitoredFileOperationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataRefreshService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-ui/src/app/bookdrop/bookdrop-file-metadata-picker-component/bookdrop-file-metadata-picker.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
Labels: enhancement

#1147 Remove EPUB reader transparency
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
Labels: ui-tweaks

#1148 Add EPUB reader progress tracking and auto-update read status
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
Labels: feature

#1149 Add read status icons to book card and book browser table
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.scss
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/book-browser/table-column-preference-service.ts
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/helpers/read-status.helper.ts
Labels: feature

#1133 feat: ctrl+click on the book cover will select the book
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
Labels: enhancement

#1150 Add note specifying the maximum file size allowed for the background …
  booklore-ui/src/app/layout/component/theme-configurator/upload-dialog/upload-dialog.component.html
Labels: chore

#1160 Rollback background blur and transparency due to high CPU/GPU usage
  booklore-api/src/test/java/com/adityachandel/booklore/service/metadata/extractor/CbxMetadataExtractorTest.java
  booklore-ui/src/app/app.component.html
  booklore-ui/src/app/app.component.scss
  booklore-ui/src/app/app.component.ts
  booklore-ui/src/app/core/model/app-state.model.ts
  booklore-ui/src/app/core/service/app-config.service.ts
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.html
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.scss
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.ts
  booklore-ui/src/assets/layout/styles/layout/_topbar.scss
Labels: bug

#1161 Optimize topbar search for better performance
  booklore-ui/src/app/book/components/book-browser/filters/HeaderFilter.ts
  booklore-ui/src/app/book/components/book-searcher/book-searcher.component.ts
Labels: enhancement

#1162 Merge develop into master for the release
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/MonitoredFileOperationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataRefreshService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/extractor/CbxMetadataExtractor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/metadata/extractor/CbxMetadataExtractorTest.java
  booklore-ui/src/app/app.component.html
  booklore-ui/src/app/app.component.scss
  booklore-ui/src/app/app.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.scss
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.scss
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/HeaderFilter.ts
  booklore-ui/src/app/book/components/book-browser/table-column-preference-service.ts
  booklore-ui/src/app/book/components/book-searcher/book-searcher.component.ts
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
  booklore-ui/src/app/book/helpers/read-status.helper.ts
  booklore-ui/src/app/bookdrop/bookdrop-file-metadata-picker-component/bookdrop-file-metadata-picker.component.ts
  booklore-ui/src/app/core/model/app-state.model.ts
  booklore-ui/src/app/core/service/app-config.service.ts
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.html
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.scss
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.ts
  booklore-ui/src/app/layout/component/theme-configurator/upload-dialog/upload-dialog.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/assets/layout/styles/layout/_topbar.scss
Labels: patch, skip changelog

#1165 Hardcover: Pick correct ISBN from the response
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
Labels: chore

#1167 Filter "Continue Reading" to only show READING, RE_READING, or PAUSED…
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.ts
Labels: enhancement

#1170 Merge develop into master for the release
  booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookDropService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookdropMonitoringService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/UnifiedFileMoveService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/watcher/LibraryFileEventProcessor.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/bookdrop/BookDropServiceTest.java
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.ts
Labels: patch, skip changelog

#1177 Fix: encode URI params for series names with special characters
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.ts
Labels: enhancement

#1205 Remove metadata backup process
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/MetadataPersistenceSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/SettingPersistenceHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-persistence-settings-component/metadata-persistence-settings-component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-persistence-settings-component/metadata-persistence-settings-component.ts
Labels: chore

#1203 Fix: send default instapaper properties in the kobo initialization
  booklore-api/src/main/java/com/adityachandel/booklore/service/kobo/KoboResourcesComponent.java
Labels: bug

#1201 fix: stop sending shelves not associated with the user
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/ShelfMapper.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/v2/BookMapperV2.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
Labels: bug

#1210 Add ability to move books across libraries
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/FileMoveRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/BookRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/LibraryPathRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/FileMoveService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/FileMovingHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/UnifiedFileMoveService.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/file/FileMoveServiceTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/file/UnifiedFileMoveServiceTest.java
  booklore-ui/src/app/book/components/book-browser/BookDialogHelperService.ts
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/utilities/component/file-mover-component/file-mover-component.html
  booklore-ui/src/app/utilities/component/file-mover-component/file-mover-component.ts
  booklore-ui/src/app/utilities/service/file-operations-service.ts
Labels: feature

#1211 Display library name in metadata viewer page
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/BookMapper.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/v2/BookMapperV2.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/Book.java
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
Labels: enhancement

#1217 Default to ISBN13 in metadata search
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-searcher/metadata-searcher.component.ts
Labels: enhancement

#1223 Add more primary and surface colors
  booklore-ui/src/app/core/service/app-config.service.ts
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.ts
  booklore-ui/src/app/layout/component/theme-palette-extend.ts
Labels: ui-tweaks

#1226 Ensure temporary files are properly cleaned up after metadata updates
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/writer/CbxMetadataWriter.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/writer/EpubMetadataWriter.java
Labels: bug

#1234 Fix: Enter key in bulk metadata edit triggers form submit instead of …
  booklore-ui/src/app/metadata/bulk-metadata-update-component/bulk-metadata-update-component.html
  booklore-ui/src/app/metadata/bulk-metadata-update-component/bulk-metadata-update-component.ts
Labels: bug
