Repository booklore-app/booklore, pull requests merged in 2025-07, with the labels that each got.

#633 Fix font size not applying on initial load in EPUB viewer
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
Labels: bug

#637 Fix missing app version in latest Docker image tag
  .github/workflows/docker-build-publish.yml
Labels: bug

#638 Merge Develop into Master for release
  .github/workflows/docker-build-publish.yml
  booklore-api/build.gradle
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/LibraryEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/test/java/com/adityachandel/booklore/BookServiceDeleteTests.java
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
Labels: documentation, patch

#641 Display first book in series when collapsed
  .github/release-drafter.yml
  booklore-ui/src/app/book/components/book-browser/filters/SeriesCollapseFilter.ts
Labels: enhancement

#647 Fix Transaction Deadlock During Library Re-Scan Due to Duplicates
  booklore-api/src/main/java/com/adityachandel/booklore/model/websocket/Topic.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/FileMoveService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/AbstractFileProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/FileProcessingUtils.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryProcessingService.java
  booklore-ui/src/app/app.component.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: bug

#649 Improve Aesthetics of Login and Admin Setup Views
  booklore-ui/src/app/app.component.ts
  booklore-ui/src/app/core/component/login/login.component.html
  booklore-ui/src/app/core/component/login/login.component.scss
  booklore-ui/src/app/core/component/login/login.component.ts
  booklore-ui/src/app/core/service/app-config.service.ts
  booklore-ui/src/app/core/setup/setup.component.html
  booklore-ui/src/app/core/setup/setup.component.scss
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.ts
  booklore-ui/src/main.ts
Labels: enhancement

#650 Merge Develop into Master for release
  booklore-api/src/main/java/com/adityachandel/booklore/model/websocket/Topic.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/FileMoveService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/AbstractFileProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/FileProcessingUtils.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryProcessingService.java
  booklore-ui/src/app/app.component.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/core/component/login/login.component.html
  booklore-ui/src/app/core/component/login/login.component.scss
  booklore-ui/src/app/core/component/login/login.component.ts
  booklore-ui/src/app/core/service/app-config.service.ts
  booklore-ui/src/app/core/setup/setup.component.html
  booklore-ui/src/app/core/setup/setup.component.scss
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.ts
  booklore-ui/src/main.ts
Labels: documentation, minor

#657 Remove lock icon from the book card
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/core/setup/setup.component.ts
Labels: chore

#661 Improve UI compatibility for mobile devices
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.scss
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.html
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/SeriesCollapseFilter.ts
  booklore-ui/src/app/book/components/book-searcher/book-searcher.component.html
  booklore-ui/src/app/book/components/book-searcher/book-searcher.component.scss
  booklore-ui/src/app/book/components/book-searcher/book-searcher.component.ts
  booklore-ui/src/app/book/components/book-sender/book-sender.component.html
  booklore-ui/src/app/book/components/library-creator/library-creator.component.html
  booklore-ui/src/app/book/components/library-creator/library-creator.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/book-metadata-center.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-picker/metadata-picker.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.html
  booklore-ui/src/app/core/component/login/login.component.html
  booklore-ui/src/app/dashboard/components/dashboard-scroller/dashboard-scroller.component.scss
  booklore-ui/src/app/layout/component/layout-main/app.layout.component.ts
  booklore-ui/src/app/layout/component/layout-main/service/app.layout.service.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
  booklore-ui/src/app/settings/global-preferences/file-upload-pattern/file-upload-pattern.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-settings.component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.html
  booklore-ui/src/app/settings/user-management/user-management.component.html
  booklore-ui/src/app/utilities/component/book-uploader/book-uploader.component.html
  booklore-ui/src/app/utilities/component/directory-picker/directory-picker.component.html
  booklore-ui/src/app/utilities/component/directory-picker/directory-picker.component.scss
  booklore-ui/src/assets/layout/styles/layout/_responsive.scss
  booklore-ui/src/assets/layout/styles/layout/_topbar.scss
Labels: enhancement

#669 Add CONTRIBUTING.md with project setup and contribution guidelines
  CONTRIBUTING.md
Labels: documentation

#671 Add ability to reset reading progress for a book
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: enhancement

#675 Merge Develop into Master for release
  CONTRIBUTING.md
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/custom/BookLoreUserTransformer.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookLoreUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/UserSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/UserBookProgressEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/DefaultUserSettingsProvider.java
  booklore-api/src/main/resources/db/migration/V36__Add_read_status_to_user_book_progress.sql
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/book-browser/table-column-preference-service.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.scss
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-picker/metadata-picker.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
Labels: documentation, patch

#681 Fix read status filter showing only “Unknown” with no results
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/SidebarFilter.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: bug

#683 Merge Develop into Master for release
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.html
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/SidebarFilter.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: documentation, patch

#708 Add support for bulk reading progress reset
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: enhancement

#710 Add support for updating read status of multiple books at once
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/ReadStatusUpdateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/service/book-menu.service.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: enhancement

#713 Restore “Page Count” field in book edit form
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
Labels: enhancement

#727 Icon Changes
  assets/favicons/android-chrome-192x192.png
  assets/favicons/android-chrome-512x512.png
  assets/favicons/apple-touch-icon-114x114.png
  assets/favicons/apple-touch-icon-120x120.png
  assets/favicons/apple-touch-icon-144x144.png
  assets/favicons/apple-touch-icon-152x152.png
  assets/favicons/apple-touch-icon-167x167.png
  assets/favicons/apple-touch-icon-180x180.png
  assets/favicons/apple-touch-icon-57x57.png
  assets/favicons/apple-touch-icon-60x60.png
  assets/favicons/apple-touch-icon-72x72.png
  assets/favicons/apple-touch-icon-76x76.png
  assets/favicons/favicon-128x128.png
  assets/favicons/favicon-16x16.png
  assets/favicons/favicon-196x196.png
  assets/favicons/favicon-32x32.png
  assets/favicons/favicon-96x96.png
  assets/favicons/mstile-144x144.png
  assets/favicons/mstile-150x150.png
  assets/favicons/mstile-310x150.png
  assets/favicons/mstile-310x310.png
  assets/favicons/mstile-70x70.png
  assets/logo with text.svg
Labels: enhancement

#739 Improve metadata editor layout
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-editor/metadata-editor.component.html
Labels: chore

#741 Adds Upload Status Label and Instructions for Book Uploads
  booklore-ui/src/app/utilities/component/book-uploader/book-uploader.component.html
Labels: chore

#742 Use 100dvh to fix layout issue in mobile devices
  booklore-ui/src/app/book/components/book-browser/book-browser.component.scss
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/cbx-reader/cbx-reader.component.scss
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
  booklore-ui/src/app/bookdrop/bookdrop-file-review-component/bookdrop-file-review.component.html
  booklore-ui/src/app/core/security/oauth2-management/authentication-settings.component.html
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.scss
  booklore-ui/src/app/metadata/book-metadata-center-component/book-metadata-center.component.html
  booklore-ui/src/app/metadata/multi-book-metadata-editor-component/multi-book-metadata-editor-component.html
  booklore-ui/src/app/settings/email/email.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.html
  booklore-ui/src/app/settings/reader-preferences/reader-preferences.component.html
  booklore-ui/src/app/settings/user-management/user-management.component.html
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences-parent.component.html
  booklore-ui/src/assets/layout/styles/layout/_content.scss
  booklore-ui/src/assets/layout/styles/layout/_main.scss
  booklore-ui/src/assets/layout/styles/layout/_menu.scss
  booklore-ui/src/assets/layout/styles/layout/_responsive.scss
Labels: bug

#744 Progressive UI Refinements for Mobile and Desktop Layouts
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.scss
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/core/security/oauth2-management/authentication-settings.component.html
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.scss
  booklore-ui/src/app/metadata/book-metadata-center-component/book-metadata-center.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/book-metadata-center.component.scss
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/settings/email/email.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/metadata-match-weights-component/metadata-match-weights-component.html
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-settings.component.html
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-settings.component.scss
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.html
  booklore-ui/src/app/settings/reader-preferences/reader-preferences.component.html
  booklore-ui/src/app/settings/settings.component.html
  booklore-ui/src/app/settings/settings.component.ts
  booklore-ui/src/app/settings/user-management/user-management.component.html
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences-parent.component.html
  booklore-ui/src/assets/layout/styles/layout/_responsive.scss
Labels: enhancement

#747 Fix dark theme detection when <html> has multiple classes
  booklore-ui/src/assets/layout/styles/layout/variables/main/_dark.scss
Labels: enhancement

#755 Persist cover scale preference per device using LocalStorage
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/cover-scale-preference.service.ts
  booklore-ui/src/app/core/service/local-storage-service.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
Labels: enhancement

#756 Move logout tooltip to left
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
Labels: enhancement

#758 Add buttons to open BookLore documentation in topbar and mobile menu
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
Labels: documentation

#762 Fix scheduled library rescan failing due to missing authentication
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/scheduler/LibraryRescanScheduler.java
Labels: bug

#766 Merge Develop into Master for release
  CONTRIBUTING.md
  README.md
  booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookDropService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/scheduler/LibraryRescanScheduler.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/upload/FileUploadService.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.scss
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/cover-scale-preference.service.ts
  booklore-ui/src/app/core/service/local-storage-service.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/book-metadata-center.component.scss
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-searcher/metadata-searcher.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-searcher/metadata-searcher.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
  booklore-ui/src/app/settings/global-preferences/user-profile-dialog/user-profile-dialog.component.html
  booklore-ui/src/assets/layout/styles/layout/variables/main/_dark.scss
Labels: documentation, patch

#771 Enhance the left sidebar with dropdown toggles for expandable menu items
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.html
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.html
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.ts
Labels: enhancement

#778 Add live demo to README
  README.md
Labels: documentation

#787 Implement magic shelves with dynamic rule-based filters
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/WebSocketAuthInterceptor.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MagicShelfController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/MagicShelf.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/MagicShelfEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/MagicShelfRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/MagicShelfService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataMatchService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/migration/AppMigrationService.java
  booklore-api/src/main/resources/db/migration/V39__Create_magic_shelf_table.sql
  booklore-ui/src/app/app.routes.ts
  booklore-ui/src/app/book-rule-evaluator.service.ts
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.html
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/book/service/library-shelf-menu.service.ts
  booklore-ui/src/app/dialog-launcher.service.ts
  booklore-ui/src/app/icon-picker-v2-component/icon-picker-v2-component.html
  booklore-ui/src/app/icon-picker-v2-component/icon-picker-v2-component.scss
  booklore-ui/src/app/icon-picker-v2-component/icon-picker-v2-component.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.html
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.html
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
  booklore-ui/src/app/magic-shelf-component/magic-shelf-component.html
  booklore-ui/src/app/magic-shelf-component/magic-shelf-component.scss
  booklore-ui/src/app/magic-shelf-component/magic-shelf-component.ts
  booklore-ui/src/app/magic-shelf-service.ts
  booklore-ui/src/app/magic-shelf-utils.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/settings/global-preferences/metadata-match-weights-component/metadata-match-weights-component.html
  booklore-ui/src/app/settings/global-preferences/metadata-match-weights-component/metadata-match-weights-component.ts
  booklore-ui/src/app/sql-filter-builder.ts
  booklore-ui/src/assets/layout/styles/layout/_menu.scss
  booklore-ui/src/styles.scss
Labels: feature
