Repository booklore-app/booklore, pull requests merged in 2025-05, with the labels that each got.

#245 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/AuthenticationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/JwtUtils.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/RefreshTokenEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/RefreshTokenRepository.java
  booklore-api/src/main/resources/db/migration/V11__Create_refresh_token_table.sql
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
  booklore-ui/src/app/book/components/pdf-viewer/pdf-viewer.component.ts
  booklore-ui/src/app/core/component/change-password/change-password.component.ts
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.html
  booklore-ui/src/app/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.html
  booklore-ui/src/app/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.html
  booklore-ui/src/app/settings/admin/create-user-dialog/create-user-dialog.component.scss
  booklore-ui/src/app/settings/book-preferences/book-preferences.component.ts
  booklore-ui/src/app/settings/email/email-provider/email-provider.component.html
  booklore-ui/src/app/settings/email/email-recipient/email-recipient.component.html
  booklore-ui/src/app/settings/global-preferences/file-upload-pattern/file-upload-pattern.component.html
  booklore-ui/src/app/settings/global-preferences/file-upload-pattern/file-upload-pattern.component.scss
  booklore-ui/src/app/settings/global-preferences/file-upload-pattern/file-upload-pattern.component.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-settings.component.html
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-settings.component.scss
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-settings.component.ts
  booklore-ui/src/app/settings/global-preferences/opds-settings/opds-user.service.ts
  booklore-ui/src/app/settings/global-preferences/user-profile-dialog/user-profile-dialog.component.html
  booklore-ui/src/app/settings/global-preferences/user-profile-dialog/user-profile-dialog.component.scss
  booklore-ui/src/app/settings/global-preferences/user-profile-dialog/user-profile-dialog.component.ts
  booklore-ui/src/app/settings/settings.component.html
  booklore-ui/src/app/settings/settings.component.ts
  booklore-ui/src/app/settings/user-management/create-user-dialog/create-user-dialog.component.html
  booklore-ui/src/app/settings/user-management/create-user-dialog/create-user-dialog.component.scss
  booklore-ui/src/app/settings/user-management/create-user-dialog/create-user-dialog.component.ts
  booklore-ui/src/app/settings/user-management/user-management.component.html
  booklore-ui/src/app/settings/user-management/user-management.component.scss
  booklore-ui/src/app/settings/user-management/user-management.component.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
Labels: documentation

#252 Implement multi-select AND filter with count in UI
  booklore-api/src/main/resources/application.yaml
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.html
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
Labels: feature

#253 Make main dashboard vertically scrollable
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.html
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.scss
Labels: bug

#254 Merge Develop into Master for the Release
  booklore-api/build.gradle
  booklore-api/src/main/resources/application.yaml
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.html
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.html
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.scss
  booklore-ui/src/app/settings/user-management/user-management.component.ts
Labels: documentation, minor

#261 Fix strictdiscoverydocumentvalidation error
  booklore-ui/src/app/auth-initializer.ts
Labels: bug, patch

#263 Merge Develop into Master for the Release
  booklore-ui/src/app/auth-initializer.ts
Labels: documentation, patch

#264 Use correct WebSocket protocol (wss) based on current page protocol
  booklore-ui/src/environments/environment.prod.ts
Labels: bug

#265 Merge Develop into Master for the Release
  booklore-ui/src/environments/environment.prod.ts
Labels: documentation, patch

#268 Merge Develop into Master for the Release
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
Labels: documentation, patch

#270 Fix incorrect background color in light OS theme
  booklore-ui/src/assets/layout/styles/layout/variables/main/_dark.scss
Labels: bug

#271 Merge Develop into Master for Release
  booklore-ui/src/assets/layout/styles/layout/variables/main/_dark.scss
Labels: documentation, patch

#277 Add “Unassigned” shelf view for books not in any shelf
  booklore-ui/src/app/app.routes.ts
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/service/shelf.service.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.html
Labels: feature, minor

#280 Increase column lengths across multiple tables for flexibility
  booklore-api/src/main/java/com/adityachandel/booklore/service/VersionService.java
  booklore-api/src/main/resources/db/migration/V16__Widen_selected_column_sizes.sql
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
Labels: patch, cleanup

#283 Enable editing existing admin users, creating new admins, and deletin…
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/AuthenticationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/exception/ApiError.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/UserCreateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserProvisioningService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserService.java
  booklore-ui/src/app/app.routes.ts
  booklore-ui/src/app/auth-interceptor.service.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/settings/user-management/create-user-dialog/create-user-dialog.component.html
  booklore-ui/src/app/settings/user-management/create-user-dialog/create-user-dialog.component.ts
  booklore-ui/src/app/settings/user-management/user-management.component.html
  booklore-ui/src/app/settings/user-management/user-management.component.ts
Labels: enhancement, minor

#284 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/AuthenticationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/exception/ApiError.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/UserCreateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserProvisioningService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserService.java
  booklore-ui/src/app/app.routes.ts
  booklore-ui/src/app/auth-interceptor.service.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/settings/user-management/create-user-dialog/create-user-dialog.component.html
  booklore-ui/src/app/settings/user-management/create-user-dialog/create-user-dialog.component.ts
  booklore-ui/src/app/settings/user-management/user-management.component.html
  booklore-ui/src/app/settings/user-management/user-management.component.ts
Labels: documentation, minor

#285 Add infinite scroll on epub reader in mobile view
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
Labels: enhancement, minor

#287 fix: firefox layout issue
  booklore-ui/src/assets/layout/styles/layout/_responsive.scss
Labels: bug, patch

#289 Marge Develop into Master for Release
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
  booklore-ui/src/assets/layout/styles/layout/_responsive.scss
Labels: documentation, minor

#291 Add support for paginated and scrolled modes in EPUB reader
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookLoreUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/EpubViewerPreferences.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/EpubViewerPreferencesEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BooksService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserProvisioningService.java
  booklore-api/src/main/resources/db/migration/V17__Add_flow_column_to_epub_viewer_preference.sql
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
  booklore-ui/src/app/settings/user-preferences/user-preferences.component.html
  booklore-ui/src/app/settings/user-preferences/user-preferences.component.ts
Labels: feature, minor

#298 Fix manage library and admin permissions
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/UserUpdateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserService.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/book-metadata-center.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.html
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.ts
  booklore-ui/src/app/settings/user-management/user-management.component.html
Labels: bug, patch

#304 Add user specific book progress tracking and improve epub progress tracking
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/Book.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/EpubProgress.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/PdfProgress.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/ReadProgressRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/UserBookProgressEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BooksService.java
  booklore-api/src/main/resources/db/migration/V18__Add_progress_percent_columns_to_user_book_progress.sql
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
  booklore-ui/src/app/book/components/pdf-viewer/pdf-viewer.component.html
  booklore-ui/src/app/book/components/pdf-viewer/pdf-viewer.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: feature, minor

#301 Fix EPUB Cover Image Detection
  .gitignore
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java
Labels: enhancement

#307 Remove unwanted black bar at bottom of EPUB viewer after loading
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
Labels: bug, minor

#310 Widen length of metadata fields and add checks in the code
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/PdfProcessor.java
  booklore-api/src/main/resources/db/migration/V19__Widen_selected_column_sizes_even_more.sql
Labels: enhancement, patch

#309 fix: restore remote auth
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/auth-initializer.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/core/service/auth.service.ts
Labels: bug, patch

#314 Merge Develop into Master for Release
  .gitignore
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/Book.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookLoreUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/EpubProgress.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/EpubViewerPreferences.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/PdfProgress.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/ReadProgressRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/UserUpdateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/EpubViewerPreferencesEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/UserBookProgressEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BooksService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/PdfProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserProvisioningService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserService.java
  booklore-api/src/main/resources/db/migration/V17__Add_flow_column_to_epub_viewer_preference.sql
  booklore-api/src/main/resources/db/migration/V18__Add_progress_percent_columns_to_user_book_progress.sql
  booklore-api/src/main/resources/db/migration/V19__Widen_selected_column_sizes_even_more.sql
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/auth-initializer.ts
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
  booklore-ui/src/app/book/components/pdf-viewer/pdf-viewer.component.html
  booklore-ui/src/app/book/components/pdf-viewer/pdf-viewer.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/book-metadata-center.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/core/service/auth.service.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.html
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.ts
  booklore-ui/src/app/settings/user-management/user-management.component.html
  booklore-ui/src/app/settings/user-management/user.service.ts
  booklore-ui/src/app/settings/user-preferences/user-preferences.component.html
  booklore-ui/src/app/settings/user-preferences/user-preferences.component.ts
Labels: documentation, minor

#317 Add custom startup banner for spring boot app
  booklore-api/src/main/resources/banner.txt
Labels: patch, cleanup

#321 Empty stars shown when one rating is missing
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
Labels: bug

#323 Merge Develop into Master for Release
  README.md
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/DualJwtAuthenticationFilter.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/exception/ApiError.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/EmailProvider.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/CreateEmailProviderRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/EmailProviderEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/EmailService.java
  booklore-api/src/main/resources/banner.txt
  booklore-api/src/main/resources/db/migration/V20__Add_from_address_to_email_provider.sql
  booklore-ui/src/app/book/components/book-sender/book-sender.component.ts
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/settings/email/create-email-provider-dialog/create-email-provider-dialog.component.html
  booklore-ui/src/app/settings/email/create-email-provider-dialog/create-email-provider-dialog.component.ts
  booklore-ui/src/app/settings/email/email-provider/email-provider.component.html
  booklore-ui/src/app/settings/email/email-provider/email-provider.model.ts
Labels: documentation, patch

#331 Hotfix OPDS throwing 403 error
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/DualJwtAuthenticationFilter.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
Labels: bug, patch

#332 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/DualJwtAuthenticationFilter.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookMetadataEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-api/src/main/resources/db/migration/V21__Change_series_number_to_float_in_book_metadata.sql
Labels: documentation, patch

#343 Ensure updated and deleted books reflect correctly in library view
  booklore-api/src/main/java/com/adityachandel/booklore/service/LibraryProcessingService.java
Labels: bug

#344 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/service/LibraryProcessingService.java
Labels: documentation, patch

#348 Refine handling of file create/delete events in library watcher
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/LibraryProcessingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/monitoring/MonitoringService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/monitoring/MonitoringTask.java
  booklore-api/src/main/java/com/adityachandel/booklore/util/FileUtils.java
Labels: bug

#362 Add sorting option: Title followed by Series
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/service/sort.service.ts
Labels: enhancement

#369 Enhance file path display with collapsible toggle and styled file typ…
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: enhancement

#370 Merge Develop into Master for Release
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: documentation, patch

#373 Remove deprecated rating box from the UI
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-picker/metadata-picker.component.ts
Labels: cleanup

#375 Support per-library and per-shelf sorting and view preferences
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/custom/BookLoreUserTransformer.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookLoreUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/UserSettingKey.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/service/library.service.ts
  booklore-ui/src/app/settings/reader-preferences/reader-preferences.component.html
  booklore-ui/src/app/settings/reader-preferences/reader-preferences.component.scss
  booklore-ui/src/app/settings/reader-preferences/reader-preferences.component.ts
  booklore-ui/src/app/settings/settings.component.html
  booklore-ui/src/app/settings/settings.component.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-sorting-preferences/sidebar-sorting-preferences.component.html
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-sorting-preferences/sidebar-sorting-preferences.component.scss
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-sorting-preferences/sidebar-sorting-preferences.component.ts
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences-parent.component.html
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences-parent.component.scss
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences-parent.component.ts
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences/view-preferences.component.html
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences/view-preferences.component.scss
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences/view-preferences.component.ts
Labels: feature

#377 Optimize Settings logic to avoid duplicate service calls
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/core/security/oauth2-management/authentication-settings.component.ts
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.html
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/settings/global-preferences/user-profile-dialog/user-profile-dialog.component.ts
  booklore-ui/src/app/settings/reader-preferences/reader-preferences.component.ts
  booklore-ui/src/app/settings/settings.component.html
  booklore-ui/src/app/settings/user-management/user-management.component.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-sorting-preferences/sidebar-sorting-preferences.component.ts
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences/view-preferences.component.ts
Labels: cleanup

#379 Support uploading comic book archives (CBZ, CBR, CB7)
  booklore-api/src/main/java/com/adityachandel/booklore/service/FileUploadService.java
Labels: feature

#381 Fix LazyInitializationException error
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/LibraryPathEntity.java
Labels: bug

#389 Support Hardcover as metadata provider
  booklore-api/src/main/java/com/adityachandel/booklore/config/BookParserConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/MetadataProviderSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookMetadataEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/enums/MetadataProvider.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/hardcover/GraphQLRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/hardcover/GraphQLResponse.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/hardcover/HardcoverBookSearchService.java
  booklore-api/src/main/resources/db/migration/V25__Add_hardcover_rating_columns.sql
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.ts
  booklore-ui/src/app/book/metadata/model/provider.model.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.html
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.scss
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.ts
  booklore-ui/src/app/settings/settings.component.html
  booklore-ui/src/app/settings/settings.component.ts
Labels: feature

#391 Enhance Quick Metadata Refresh Functionality
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/hardcover/HardcoverBookSearchService.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.html
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.ts
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-fetch-options/metadata-fetch-options.component.html
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-fetch-options/metadata-fetch-options.component.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
Labels: enhancement

#392 Merge Develop into Master for Release v0.13.0
  booklore-api/src/main/java/com/adityachandel/booklore/config/BookParserConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/MetadataProviderSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookMetadataEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/enums/MetadataProvider.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookCreatorService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/hardcover/GraphQLRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/hardcover/GraphQLResponse.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/hardcover/HardcoverBookSearchService.java
  booklore-api/src/main/resources/db/migration/V25__Add_hardcover_rating_columns.sql
  booklore-ui/src/app/auth-initializer.ts
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.html
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.ts
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-fetch-options/metadata-fetch-options.component.html
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-fetch-options/metadata-fetch-options.component.ts
  booklore-ui/src/app/book/metadata/model/provider.model.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.html
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.scss
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.ts
  booklore-ui/src/app/settings/settings.component.html
  booklore-ui/src/app/settings/settings.component.ts
Labels: documentation, minor

#394 Added support for extracting and displaying .webp files from comic book archives
  booklore-api/src/main/java/com/adityachandel/booklore/service/CbxReaderService.java
  booklore-ui/src/app/book/service/book.service.ts
Labels: enhancement

#400 Leverage fuzzy logic for more accurate metadata resolution and support Amazon cookies
  booklore-api/build.gradle
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/MetadataProviderSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.html
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.ts
Labels: enhancement

#403 Further enhance metadata matching precision
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
Labels: enhancement

#404 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
Labels: documentation, patch

#409 Add filters and columns for hardcover rating and review count
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/service/sort.service.ts
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences/view-preferences.component.ts
Labels: feature

#410 feat(metadata-lock): add UI for toggling individual field locks with …
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MetadataController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/ToggleFieldLocksRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataService.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/lock-unlock-metadata-dialog/lock-unlock-metadata-dialog.component.html
  booklore-ui/src/app/book/components/book-browser/lock-unlock-metadata-dialog/lock-unlock-metadata-dialog.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: feature

#412 Add more metadata fields to quick metadata refresh feature
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/MetadataRefreshOptions.java
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.html
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.ts
  booklore-ui/src/app/book/metadata/model/request/metadata-refresh-options.model.ts
Labels: enhancement
