Repository booklore-app/booklore, pull requests merged in 2025-10, with the labels that each got.

#1254 Resolve Kobo Library Synchronization Issue
  nginx.conf
Labels: bug

#1255 Merge develop into the master for release
  nginx.conf
Labels: patch, skip changelog

#1263 Enhance metadata options to allow skipping fields during fetch and support extended field options
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/MetadataRefreshOptions.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/SettingPersistenceHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataRefreshService.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/metadata/MetadataRefreshServiceTest.java
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.html
  booklore-ui/src/app/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.ts
  booklore-ui/src/app/metadata/model/request/metadata-refresh-options.model.ts
  booklore-ui/src/app/settings/library-metadata-settings-component/library-metadata-settings.component.ts
Labels: feature

#1265 Improved EPUB navigation on mobile devices with swipe gestures
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
Labels: enhancement

#1267 Implement EPUB page spread feature for desktop
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookLoreUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/EpubViewerPreferences.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/MetadataRefreshOptions.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/EpubViewerPreferencesEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/SettingPersistenceHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataRefreshService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/DefaultUserSettingsProvider.java
  booklore-api/src/main/resources/db/migration/V54__Add_Spread_Column_Epub.sql
  booklore-api/src/test/java/com/adityachandel/booklore/service/metadata/MetadataRefreshServiceTest.java
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.html
  booklore-ui/src/app/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.ts
  booklore-ui/src/app/metadata/model/request/metadata-refresh-options.model.ts
  booklore-ui/src/app/settings/library-metadata-settings-component/library-metadata-settings.component.html
  booklore-ui/src/app/settings/reader-preferences/cbx-reader-preferences-component/cbx-reader-preferences-component.scss
  booklore-ui/src/app/settings/reader-preferences/cbx-reader-preferences-component/cbx-reader-preferences-component.ts
  booklore-ui/src/app/settings/reader-preferences/epub-reader-preferences-component/epub-reader-preferences-component.html
  booklore-ui/src/app/settings/reader-preferences/epub-reader-preferences-component/epub-reader-preferences-component.scss
  booklore-ui/src/app/settings/reader-preferences/epub-reader-preferences-component/epub-reader-preferences-component.ts
  booklore-ui/src/app/settings/reader-preferences/pdf-reader-preferences-component/pdf-reader-preferences-component.scss
  booklore-ui/src/app/settings/user-management/user.service.ts
Labels: feature

#1270 Resolve CBX page sequence issue
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookMediaController.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/reader/CbxReaderService.java
Labels: bug

#1273 Add step-by-step documentation for setting up email integration
  booklore-ui/src/app/settings/email/email-provider/email-provider.component.html
  booklore-ui/src/app/settings/email/email-provider/email-provider.component.scss
  booklore-ui/src/app/settings/email/email-provider/email-provider.component.ts
Labels: documentation

#1274 Add OPDS setup and usage documentation
  booklore-ui/src/app/settings/opds-settings-v2/opds-settings-v2.html
  booklore-ui/src/app/settings/opds-settings-v2/opds-settings-v2.scss
  booklore-ui/src/app/settings/opds-settings-v2/opds-settings-v2.ts
Labels: documentation

#1277 Upgrade project environment to Java 25 and Gradle 9
  Dockerfile
  booklore-api/build.gradle
  booklore-api/gradle/wrapper/gradle-wrapper.jar
  booklore-api/gradle/wrapper/gradle-wrapper.properties
  booklore-api/gradlew
  booklore-api/gradlew.bat
  booklore-api/src/test/java/com/adityachandel/booklore/service/bookdrop/BookDropServiceTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/util/builder/LibraryTestBuilder.java
Labels: dependencies

#1275 Feat: set reading status using Koreader Sync Plugin
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
Labels: enhancement

#1282 Fix book opening issue when KOReader progress is sent
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/KoreaderService.java
Labels: bug

#1289 Fix: Books publish date incorrect when moved
  booklore-ui/src/app/utilities/component/file-mover-component/file-mover-component.ts
Labels: bug
