Repository booklore-app/booklore, pull requests merged in 2025-08, with the labels that each got.

#817 feat(bookdrop): add full pagination support with select-all and metad…
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookdropFileController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/BookdropFinalizeRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/BookdropSelectionRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/BookdropFileRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookDropService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookdropEventHandlerService.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/BookDropServiceTest.java
  booklore-ui/src/app/bookdrop/bookdrop-file-metadata-picker-component/bookdrop-file-metadata-picker.component.html
  booklore-ui/src/app/bookdrop/bookdrop-file-review-component/bookdrop-file-review.component.html
  booklore-ui/src/app/bookdrop/bookdrop-file-review-component/bookdrop-file-review.component.ts
  booklore-ui/src/app/bookdrop/bookdrop-file-task.service.ts
Labels: enhancement

#818 feat: prevent series collapsing when series filter is applied via URL
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/SeriesCollapseFilter.ts
Labels: enhancement

#822 feat: add ability to clear personal rating and reset read status to U…
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.ts
Labels: enhancement

#828 fix: push GHCR image to repo-level path
  .github/workflows/docker-build-publish.yml
Labels: ci

#844 Fixed issue with not updating the book finished date when updating read status
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
Labels: bug

#850 Allow book upload GUI to upload into Bookdrop
  booklore-api/src/main/java/com/adityachandel/booklore/controller/FileUploadController.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/AbstractFileProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryProcessingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/upload/FileUploadService.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/upload/FileUploadServiceTest.java
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/utilities/component/book-uploader/book-uploader.component.html
  booklore-ui/src/app/utilities/component/book-uploader/book-uploader.component.ts
  booklore-ui/src/app/utilities/component/file-mover-component/file-mover-component.html
Labels: feature

#851 Update Frontend and Backend Dependencies - August 2025
  booklore-api/build.gradle
  booklore-ui/package-lock.json
  booklore-ui/package.json
Labels: dependencies

#857 Fix memory leak in bulk metadata refresh process
  booklore-api/src/main/java/com/adityachandel/booklore/repository/BookRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataRefreshService.java
Labels: bug

#859 Implement live progress tracking for bulk metadata refresh (remaining…
  booklore-api/src/main/java/com/adityachandel/booklore/controller/TaskController.java
  booklore-api/src/main/java/com/adityachandel/booklore/exception/GlobalExceptionHandler.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/TaskMessage.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/enums/EventTaskType.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/enums/TaskStatus.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/websocket/Topic.java
  booklore-api/src/main/java/com/adityachandel/booklore/quartz/JobSchedulerService.java
  booklore-api/src/main/java/com/adityachandel/booklore/quartz/RefreshMetadataJob.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataRefreshService.java
  booklore-ui/src/app/app.component.ts
  booklore-ui/src/app/bookdrop/bookdrop-files-widget-component/bookdrop-files-widget.component.html
  booklore-ui/src/app/bookdrop/bookdrop-files-widget-component/bookdrop-files-widget.component.ts
  booklore-ui/src/app/core/component/live-notification-box/live-notification-box.component.html
  booklore-ui/src/app/core/component/live-notification-box/live-notification-box.component.ts
  booklore-ui/src/app/core/component/live-task-event-box/live-task-event-box.component.html
  booklore-ui/src/app/core/component/live-task-event-box/live-task-event-box.component.scss
  booklore-ui/src/app/core/component/live-task-event-box/live-task-event-box.component.ts
  booklore-ui/src/app/core/component/unified-notification-popover-component/unified-notification-popover-component.html
  booklore-ui/src/app/core/component/unified-notification-popover-component/unified-notification-popover-component.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
  booklore-ui/src/app/shared/services/task.service.ts
  booklore-ui/src/app/shared/websocket/model/log-notification.model.ts
  booklore-ui/src/app/shared/websocket/task-event.service.ts
Labels: enhancement

#860 Fix: Navigating Booklore on a new device requires refreshes
  booklore-ui/src/app/bookdrop/bookdrop-file.service.ts
  booklore-ui/src/app/core/service/auth.service.ts
  booklore-ui/src/app/core/service/startup.service.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
  booklore-ui/src/app/utilities/component/github-support-dialog/github-support-dialog.html
  booklore-ui/src/main.ts
Labels: bug

#877 Merge Develop into Master for release
  .github/release-drafter.yml
  Dockerfile
Labels: documentation, patch

#881 feat: move the series count overlay & add title tooltip
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
Labels: enhancement

#884 Implement file moving based on library naming rules, falling back to …
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/FileMoveRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/FileMoveService.java
  booklore-api/src/test/java/com/adityachandel/booklore/FileMoveServiceMoveFilesTest.java
  booklore-ui/src/app/book/components/book-browser/BookDialogHelperService.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/SeriesCollapseFilter.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/utilities/component/file-mover-component/file-mover-component.html
  booklore-ui/src/app/utilities/component/file-mover-component/file-mover-component.ts
  booklore-ui/src/app/utilities/service/file-operations-service.ts
Labels: enhancement

#873 Feature/update date finished date
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/ReadProgressRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.ts
Labels: enhancement

#887 Merge Develop into Master for release
  .github/release-drafter.yml
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/FileMoveRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/ReadProgressRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/file/FileMoveService.java
  booklore-api/src/test/java/com/adityachandel/booklore/FileMoveServiceMoveFilesTest.java
  booklore-ui/src/app/book/components/book-browser/BookDialogHelperService.ts
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/SeriesCollapseFilter.ts
  booklore-ui/src/app/book/components/book-card-lite/book-card-lite-component.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/book/service/library-shelf-menu.service.ts
  booklore-ui/src/app/book/service/library.service.ts
  booklore-ui/src/app/book/service/shelf.service.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/core/service/auth.service.ts
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.html
  booklore-ui/src/app/dashboard/components/main-dashboard/main-dashboard.component.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.ts
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/magic-shelf-component/magic-shelf-component.ts
  booklore-ui/src/app/magic-shelf.service.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/book-metadata-center.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/metadata/multi-book-metadata-editor-component/multi-book-metadata-editor-component.ts
  booklore-ui/src/app/settings/global-preferences/user-profile-dialog/user-profile-dialog.component.ts
  booklore-ui/src/app/settings/reader-preferences/reader-preferences-service.ts
  booklore-ui/src/app/settings/reader-preferences/reader-preferences.component.ts
  booklore-ui/src/app/settings/settings.component.html
  booklore-ui/src/app/settings/user-management/user-management.component.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
  booklore-ui/src/app/settings/view-preferences-parent/meta-center-view-mode-component/meta-center-view-mode-component.ts
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-sorting-preferences/sidebar-sorting-preferences.component.ts
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences/view-preferences.component.ts
  booklore-ui/src/app/utilities/component/file-mover-component/file-mover-component.html
  booklore-ui/src/app/utilities/component/file-mover-component/file-mover-component.ts
  booklore-ui/src/app/utilities/service/file-operations-service.ts
Labels: patch, skip changelog

#893 feature: add tooltips on book titles
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/book-card-lite/book-card-lite-component.html
  booklore-ui/src/app/book/components/book-card-lite/book-card-lite-component.ts
Labels: enhancement

#888 Update docker-compose.yml example file to the new booklore Docker Hub image identifier
  example-docker/docker-compose.yml
Labels: chore

#901 Fix OIDC auto-login not triggering in new browser tabs
  booklore-ui/src/app/auth-initialization-service.ts
  booklore-ui/src/app/auth-initializer.ts
  booklore-ui/src/app/core/service/auth.service.ts
  booklore-ui/src/app/core/service/startup.service.ts
Labels: bug

#904 Implement public review fetching from metadata providers
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookReviewController.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/BookReviewMapper.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/MetadataClearFlags.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookReview.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/MetadataPublicReviewsSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookMetadataEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookReviewEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/BookReviewRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookReviewService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/VersionService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/SettingPersistenceHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookReviewUpdateService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataRefreshService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-api/src/main/resources/db/migration/V44__Create_book_review_table.sql
  booklore-api/src/main/resources/db/migration/V45__Add_reviews_locked_column.sql
  booklore-api/src/main/resources/db/migration/V46__Increase_hardcover_id_length_to_512.sql
  booklore-api/src/test/java/com/adityachandel/booklore/service/BookReviewServiceTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/BookdropMetadataServiceTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/metadata/BookReviewUpdateServiceTest.java
  booklore-ui/src/app/auth-initializer.ts
  booklore-ui/src/app/book-review-service.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-card-lite/book-card-lite-component.html
  booklore-ui/src/app/book/components/book-card-lite/book-card-lite-component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/components/book-reviews/book-reviews.component.html
  booklore-ui/src/app/components/book-reviews/book-reviews.component.scss
  booklore-ui/src/app/components/book-reviews/book-reviews.component.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/core/service/settings-helper.service.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/settings/metadata-settings-component/metadata-persistence-settings-component/metadata-persistence-settings-component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-persistence-settings-component/metadata-persistence-settings-component.scss
  booklore-ui/src/app/settings/metadata-settings-component/metadata-persistence-settings-component/metadata-persistence-settings-component.ts
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.ts
  booklore-ui/src/app/settings/metadata-settings-component/public-reviews-settings-component/public-reviews-settings-component.html
  booklore-ui/src/app/settings/metadata-settings-component/public-reviews-settings-component/public-reviews-settings-component.scss
  booklore-ui/src/app/settings/metadata-settings-component/public-reviews-settings-component/public-reviews-settings-component.ts
  booklore-ui/src/app/settings/settings.component.html
Labels: feature

#892 Feat: automatically set library/path if there is only one option available
  booklore-ui/src/app/bookdrop/bookdrop-file-review-component/bookdrop-file-review.component.ts
  booklore-ui/src/app/utilities/component/book-uploader/book-uploader.component.ts
Labels: enhancement

#891 feat: Add docker compose to quickly run a dev env
  CONTRIBUTING.md
  booklore-ui/package.json
  dev.docker-compose.yml
Labels: documentation

#903 Upgrade primeng to 20.0.1
  booklore-ui/angular.json
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-searcher/book-searcher.component.ts
  booklore-ui/src/app/bookdrop/bookdrop-file-metadata-picker-component/bookdrop-file-metadata-picker.component.html
  booklore-ui/src/app/bookdrop/bookdrop-file-metadata-picker-component/bookdrop-file-metadata-picker.component.ts
  booklore-ui/src/app/bookdrop/bookdrop-file-review-component/bookdrop-file-review.component.ts
  booklore-ui/src/app/core/security/oauth2-management/authentication-settings.component.ts
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.ts
  booklore-ui/src/app/magic-shelf-component/magic-shelf-component.html
  booklore-ui/src/app/magic-shelf-component/magic-shelf-component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-picker/metadata-picker.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/metadata/bulk-metadata-update-component/bulk-metadata-update-component.html
  booklore-ui/src/app/metadata/bulk-metadata-update-component/bulk-metadata-update-component.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
Labels: dependencies

#930 Add loader for book details component
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.ts
Labels: chore

#934 Refactor Bookdrop file processing to prevent orphan target files on error
  booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookDropService.java
Labels: refactor

#944 OIDC Authentication Revamp: Smarter Init, Error Handling, and Fallback
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/DualJwtAuthenticationFilter.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
  booklore-ui/src/app/auth-initializer.ts
  booklore-ui/src/app/core/component/login/login.component.html
  booklore-ui/src/app/core/component/login/login.component.ts
  booklore-ui/src/app/core/security/oauth2-management/authentication-settings.component.ts
  booklore-ui/src/app/core/service/app-settings.service.ts
  booklore-ui/src/app/core/service/auth.service.ts
  booklore-ui/src/app/public-app-settings.service.ts
Labels: enhancement

#975 Refine book card styling
  .github/release-drafter.yml
  booklore-ui/src/app/dashboard/components/dashboard-scroller/dashboard-scroller.component.scss
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.scss
Labels: ui-tweaks

#977 CBX reader styling improvements
  booklore-ui/src/app/book/components/cbx-reader/cbx-reader.component.html
  booklore-ui/src/app/book/components/cbx-reader/cbx-reader.component.scss
  booklore-ui/src/app/book/components/cbx-reader/cbx-reader.component.ts
Labels: ui-tweaks

#984 feat(search): add ISBN & genre filters; disable author/category filte…
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.scss
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.html
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/HeaderFilter.ts
  booklore-ui/src/app/book/components/book-searcher/book-searcher.component.html
  booklore-ui/src/app/book/components/book-searcher/book-searcher.component.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: enhancement

#986 Persist sidebar filter state when toggling visibility
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/HeaderFilter.ts
  booklore-ui/src/app/book/components/book-browser/filters/sidebar-filter-toggle-pref-service.ts
Labels: enhancement

#989 Merge develop into master for release
  .github/release-drafter.yml
  .github/workflows/docker-build-publish.yml
  booklore-api/src/main/resources/application.yaml
Labels: patch, skip changelog

#872 Book additional files support library (3/3)
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/Library.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/CreateLibraryRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/LibraryEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/enums/LibraryScanMode.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/FileAsBookProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/FolderAsBookFileProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryFileProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryFileProcessorRegistry.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryProcessingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryService.java
  booklore-api/src/main/resources/db/migration/V50__Add_library_scan_mode_settings.sql
  booklore-api/src/test/java/com/adityachandel/booklore/repository/BookAdditionalFileRepositoryTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/library/FolderAsBookFileProcessorExampleTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/library/FolderAsBookFileProcessorSimpleTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/service/library/FolderAsBookFileProcessorTest.java
  booklore-api/src/test/java/com/adityachandel/booklore/util/builder/LibraryTestBuilder.java
  booklore-api/src/test/java/com/adityachandel/booklore/util/builder/LibraryTestBuilderAssert.java
  booklore-ui/src/app/book/components/library-creator/library-creator.component.html
  booklore-ui/src/app/book/components/library-creator/library-creator.component.ts
  booklore-ui/src/app/book/model/library.model.ts
Labels: feature

#1005 Fix docker build tests
  .github/workflows/docker-build-publish.yml
  Dockerfile
Labels: chore

#1007 Fix: Metadata autofetch not returning any proposals
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/MetadataFetchJobEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataRefreshService.java
Labels: bug

#1008 Get 5 reviews from Amazon and Goodreads
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
Labels: chore

#1009 Fix GHA: return original names for docker tags
  .github/workflows/docker-build-publish.yml
Labels: chore, skip changelog

#1013 Allow users to disable kobo shelf
  booklore-api/src/main/java/com/adityachandel/booklore/controller/KoboController.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/KoboSettingsController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/KoboSyncSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/KoboSettingsService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/ShelfService.java
  booklore-ui/src/app/book/service/shelf.service.ts
  booklore-ui/src/app/settings/device-settings-component/kobo-sync-settings-component/kobo-sync-settings-component.html
  booklore-ui/src/app/settings/device-settings-component/kobo-sync-settings-component/kobo-sync-settings-component.ts
  booklore-ui/src/app/settings/device-settings-component/kobo.service.ts
Labels: enhancement

#1014 Add ISBN to Metadata Search
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/response/GoogleBooksApiResponse.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoogleParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-searcher/metadata-searcher.component.html
  booklore-ui/src/app/metadata/book-metadata-center-component/metadata-searcher/metadata-searcher.component.ts
  booklore-ui/src/app/metadata/model/request/fetch-metadata-request.model.ts
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.html
Labels: feature

#1018 Allow manual bookdrop folder refresh for non-local file systems
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookdropFileController.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookdropMonitoringService.java
  booklore-ui/src/app/bookdrop/bookdrop-file-review-component/bookdrop-file-review.component.html
  booklore-ui/src/app/bookdrop/bookdrop-file-review-component/bookdrop-file-review.component.ts
  booklore-ui/src/app/bookdrop/bookdrop-files-widget-component/bookdrop-files-widget.component.ts
  booklore-ui/src/app/bookdrop/bookdrop-finalize-result-dialog-component/bookdrop-finalize-result-dialog-component.ts
  booklore-ui/src/app/bookdrop/bookdrop.service.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
Labels: feature

#1016 fix: add content-type header for koreader-sync auth
  booklore-api/src/main/java/com/adityachandel/booklore/controller/KoreaderController.java
  booklore-api/src/test/java/com/adityachandel/booklore/controller/KoreaderControllerTest.java
Labels: chore

#1020 Hide sidebar by default on mobile devices
  booklore-ui/src/app/book/components/book-browser/filters/sidebar-filter-toggle-pref-service.ts
Labels: chore

#1021 Fix notifications not being delivered for OIDC users
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/filter/CoverJwtFilter.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/filter/DualJwtAuthenticationFilter.java
Labels: bug

#1022 Set RxStomp reconnect delay to 10 seconds for stable websocket reconn…
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/filter/DualJwtAuthenticationFilter.java
  booklore-ui/src/app/shared/websocket/rx-stomp.config.ts
Labels: chore

#1029 Merge pull request #847 from booklore-app/develop
  .github/workflows/docker-build-publish.yml
Labels: major, skip changelog

#1031 Try fixing versioning #2
  .github/workflows/docker-build-publish.yml
Labels: major, skip changelog
