Repository booklore-app/booklore, pull requests merged in 2025-06, with the labels that each got.

#413 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MetadataController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/MetadataRefreshOptions.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/ToggleFieldLocksRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/lock-unlock-metadata-dialog/lock-unlock-metadata-dialog.component.html
  booklore-ui/src/app/book/components/book-browser/lock-unlock-metadata-dialog/lock-unlock-metadata-dialog.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.ts
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.html
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.ts
  booklore-ui/src/app/book/metadata/model/request/metadata-refresh-options.model.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/book/service/sort.service.ts
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences/view-preferences.component.ts
Labels: documentation, minor

#416 Build a lazy-loading PDF viewer for large files
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/PdfReaderController.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/custom/BookLoreUserTransformer.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookLoreUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookViewerSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/NewPdfViewerPreferences.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/UserSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/NewPdfViewerPreferencesEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/enums/NewPdfPageSpread.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/enums/NewPdfPageViewMode.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/NewPdfViewerPreferencesRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppMigrationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppMigrationStartup.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BooksService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/PdfReaderService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserProvisioningService.java
  booklore-api/src/main/java/com/adityachandel/booklore/util/FileService.java
  booklore-api/src/main/resources/db/migration/V26__Create_new_pdf_viewer_table.sql
  booklore-ui/src/app/book/components/cbx-reader/cbx-reader.component.html
  booklore-ui/src/app/book/components/cbx-reader/cbx-reader.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/book/service/new-pdf-reader.service.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
Labels: feature

#427 Enhance the sidebar with additional filtering options
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.html
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.scss
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
Labels: feature

#429 Implement AND/OR filter mode toggle in book filters
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.html
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
Labels: feature

#431 Add an option to adjust the size of book covers in the grid view
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookLoreUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/DefaultUserSettingsProvider.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.scss
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
Labels: feature

#434 Fix UI glitch in light theme on some OS settings
  booklore-ui/src/main.ts
Labels: bug

#436 Fix: Custom email sending as non-admin user
  booklore-api/src/main/java/com/adityachandel/booklore/controller/EmailProviderController.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/EmailRecipientController.java
Labels: bug

#437 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/controller/EmailProviderController.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/EmailRecipientController.java
Labels: documentation, patch

#441 Upgrade Angular Packages to Latest Versions (June 2025)
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
Labels: dependencies

#447 Merge Develop into Master for Release
  booklore-api/build.gradle
  booklore-api/gradle/wrapper/gradle-wrapper.properties
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookMetadataEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoodReadsParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/GoogleParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/HardcoverParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/recommender/BookRecommendationService.java
  booklore-api/src/main/resources/db/migration/V27__Add_provider_book_ids_to_book_metadata.sql
  booklore-ui/package-lock.json
  booklore-ui/package.json
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/github-support-dialog/github-support-dialog.html
  booklore-ui/src/app/github-support-dialog/github-support-dialog.scss
  booklore-ui/src/app/github-support-dialog/github-support-dialog.ts
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.ts
Labels: documentation, minor

#449 Add 4th Priority (P4) Support to Metadata Fetch Options
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/MetadataRefreshOptions.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/SettingPersistenceHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/resources/db/migration/V28__Delete_quick_book_match_setting.sql
  booklore-ui/src/app/book/components/book-browser/lock-unlock-metadata-dialog/lock-unlock-metadata-dialog.component.ts
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.html
  booklore-ui/src/app/book/metadata/metadata-options-dialog/metadata-advanced-fetch-options/metadata-advanced-fetch-options.component.ts
  booklore-ui/src/app/book/metadata/model/request/metadata-refresh-options.model.ts
Labels: feature

#451 Separate metadata settings into a dedicated tab
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.scss
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.ts
  booklore-ui/src/app/settings/settings.component.html
  booklore-ui/src/app/settings/settings.component.ts
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences/view-preferences.component.html
Labels: cleanup

#461 Fix: Sorting breaks with active filters
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
Labels: bug

#469 Overlay series number on top-right of cover if present
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
Labels: feature

#474 Make Swagger UI Access Configurable for Public or Restricted Use
  README.md
  booklore-api/src/main/java/com/adityachandel/booklore/config/AppProperties.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/CustomOpdsUserDetailsService.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/ImageCacheConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/OidcTokenValidator.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/OpenApiConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/WebSocketAuthInterceptor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryService.java
  booklore-api/src/main/resources/application.yaml
Labels: documentation

#482 Display release date next to version title in changelog
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/ReleaseNote.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/VersionService.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.scss
  booklore-ui/src/app/core/service/version.service.ts
  booklore-ui/src/app/layout/component/layout-menu/version-changelog-dialog/version-changelog-dialog.component.html
  booklore-ui/src/app/layout/component/layout-menu/version-changelog-dialog/version-changelog-dialog.component.ts
Labels: chore

#485 Improve metadata quality assessment with new Metadata Match Score and…
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MetadataController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/Book.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/MetadataMatchWeights.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/SettingPersistenceHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/CbxProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/PdfProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataMatchService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/migration/AppMigrationService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/migration/AppMigrationStartup.java
  booklore-api/src/main/resources/db/migration/V29__Add_metadata_match_score_to_book.sql
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.html
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/SidebarFilter.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/metadata-match-weights-service.ts
  booklore-ui/src/app/settings/global-preferences/metadata-match-weights-component/metadata-match-weights-component.html
  booklore-ui/src/app/settings/global-preferences/metadata-match-weights-component/metadata-match-weights-component.scss
  booklore-ui/src/app/settings/global-preferences/metadata-match-weights-component/metadata-match-weights-component.ts
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.ts
Labels: feature

#488 Refactor: Improve layout and styling of Display Settings popover
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/SeriesCollapseFilter.ts
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-filter-sorting-prefs-component/sidebar-filter-sorting-prefs-component.ts
Labels: refactor

#496 Relocate sidebar filter setting to Library/Shelf header
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/cover-scale-preference.service.ts
  booklore-ui/src/app/book/components/book-browser/filters/SeriesCollapseFilter.ts
  booklore-ui/src/app/book/components/book-browser/filters/filter-sorting-preferences.service.ts
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-filter-sorting-prefs-component/sidebar-filter-sorting-prefs-component.html
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-filter-sorting-prefs-component/sidebar-filter-sorting-prefs-component.scss
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-filter-sorting-prefs-component/sidebar-filter-sorting-prefs-component.ts
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-sorting-preferences/sidebar-sorting-preferences.component.ts
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences-parent.component.html
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences-parent.component.ts
Labels: refactor

#498 Fix: restrict book query to assigned library IDs for non-admin users
  booklore-api/src/main/java/com/adityachandel/booklore/repository/BookRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookQueryService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.ts
Labels: bug

#499 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/MetadataProviderSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/repository/BookRepository.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookQueryService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/SettingPersistenceHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/cover-scale-preference.service.ts
  booklore-ui/src/app/book/components/book-browser/filters/SeriesCollapseFilter.ts
  booklore-ui/src/app/book/components/book-browser/filters/filter-sorting-preferences.service.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.ts
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.html
  booklore-ui/src/app/settings/global-preferences/metadata-provider-settings/metadata-provider-settings.component.ts
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-filter-sorting-prefs-component/sidebar-filter-sorting-prefs-component.html
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-filter-sorting-prefs-component/sidebar-filter-sorting-prefs-component.scss
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-filter-sorting-prefs-component/sidebar-filter-sorting-prefs-component.ts
  booklore-ui/src/app/settings/view-preferences-parent/sidebar-sorting-preferences/sidebar-sorting-preferences.component.ts
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences-parent.component.html
  booklore-ui/src/app/settings/view-preferences-parent/view-preferences-parent.component.ts
Labels: documentation, patch

#509 Add an option to save metadata directly into the EPUB file, along wit…
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MetadataController.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/EpubMetadataMapper.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/EpubMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/MetadataPersistenceSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/SettingPersistenceHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryProcessingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataRestorer.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/EpubMetadataReader.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/EpubMetadataWriter.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataBackupRestoreService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/util/FileService.java
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/metadata-restore-dialog-component/metadata-restore-dialog-component.html
  booklore-ui/src/app/book/components/book-browser/metadata-restore-dialog-component/metadata-restore-dialog-component.scss
  booklore-ui/src/app/book/components/book-browser/metadata-restore-dialog-component/metadata-restore-dialog-component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.ts
  booklore-ui/src/app/utilities/service/url-helper.service.ts
Labels: feature

#511 Merge Develop into Master for Release
  README.md
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MetadataController.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/EpubMetadataMapper.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/EpubMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/MetadataPersistenceSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/SettingPersistenceHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryProcessingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataRestorer.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/EpubMetadataReader.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/EpubMetadataWriter.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataBackupRestoreService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/parser/AmazonBookParser.java
  booklore-api/src/main/java/com/adityachandel/booklore/util/FileService.java
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/metadata-restore-dialog-component/metadata-restore-dialog-component.html
  booklore-ui/src/app/book/components/book-browser/metadata-restore-dialog-component/metadata-restore-dialog-component.scss
  booklore-ui/src/app/book/components/book-browser/metadata-restore-dialog-component/metadata-restore-dialog-component.ts
  booklore-ui/src/app/book/components/book-sender/book-sender.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.scss
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.ts
  booklore-ui/src/app/utilities/service/url-helper.service.ts
Labels: minor

#522 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MetadataController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookMetadataEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-ui/src/app/layout/component/layout-menu/app.menu.component.ts
Labels: documentation, patch

#525 Ignore hidden files (starting with .) while scanning library files
  booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryProcessingService.java
Labels: bug

#529 Embed original cover image in EPUB metadata
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataRestorer.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/EpubMetadataWriter.java
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
Labels: feature

#531 Support Editing Metadata for Multiple Books at Once via Bulk Edit Int…
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MetadataController.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/BulkMetadataUpdateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/MetadataBackupRestoreService.java
  booklore-ui/src/app/book/components/book-browser/BookDialogHelperService.ts
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/metadata/bulk-metadata-update-component/bulk-metadata-update-component.html
  booklore-ui/src/app/book/metadata/bulk-metadata-update-component/bulk-metadata-update-component.scss
  booklore-ui/src/app/book/metadata/bulk-metadata-update-component/bulk-metadata-update-component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: feature

#539 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/controller/CbxReaderController.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/PdfReaderController.java
Labels: minor

#546 feat(book-browser): enable shift-click multi-selection and "Select Al…
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
Labels: feature

#548 Add book deletion feature with admin permission control
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityUtil.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-api/src/main/java/com/adityachandel/booklore/exception/ApiError.java
  booklore-api/src/main/java/com/adityachandel/booklore/exception/GlobalExceptionHandler.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/custom/BookLoreUserTransformer.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookLoreUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/UserCreateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/UserUpdateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/response/BookDeletionResponse.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/UserPermissionsEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserProvisioningService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserService.java
  booklore-api/src/main/resources/db/migration/V31__Add_delete_books_permission.sql
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.scss
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/settings/user-management/user-management.component.html
  booklore-ui/src/app/settings/user-management/user.service.ts
Labels: feature

#554 Merge Develop into Master for Release
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityUtil.java
  booklore-api/src/main/java/com/adityachandel/booklore/controller/BookController.java
  booklore-api/src/main/java/com/adityachandel/booklore/exception/ApiError.java
  booklore-api/src/main/java/com/adityachandel/booklore/exception/GlobalExceptionHandler.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/custom/BookLoreUserTransformer.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/Book.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookLoreUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/UserCreateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/ReadStatusUpdateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/UserUpdateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/response/BookDeletionResponse.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettingKey.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/settings/AppSettings.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/BookMetadataEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/UserPermissionsEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/enums/ReadStatus.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/appsettings/AppSettingService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserProvisioningService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserService.java
  booklore-api/src/main/resources/db/migration/V31__Add_delete_books_permission.sql
  booklore-api/src/main/resources/db/migration/V32__Add_personal_rating_column.sql
  booklore-api/src/main/resources/db/migration/V33__Add_read_status_to_book.sql
  booklore-ui/src/app/book/components/book-browser/book-browser.component.html
  booklore-ui/src/app/book/components/book-browser/book-browser.component.scss
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/SidebarFilter.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/book-metadata-center.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
  booklore-ui/src/app/core/model/app-settings.model.ts
  booklore-ui/src/app/settings/user-management/user-management.component.html
  booklore-ui/src/app/settings/user-management/user.service.ts
Labels: documentation, minor

#559 Refactor Topbar Action Buttons for Consistency
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
Labels: chore

#564 Display the configured OIDC provider name on the login button
  booklore-ui/src/app/core/component/login/login.component.html
  booklore-ui/src/app/core/component/login/login.component.ts
Labels: chore

#565 [OPDS] Fix search option not recognized by MoonReader
  booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
Labels: bug

#567 Fix book count not fitting within the sidebar
  booklore-ui/src/app/layout/component/layout-menu/app.menuitem.component.html
  booklore-ui/src/assets/layout/styles/layout/_menu.scss
Labels: bug

#570 Fix topbar theme button
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
Labels: bug

#571 Merge Develop into Master for Release
  booklore-ui/src/app/layout/component/layout-topbar/app.topbar.component.html
Labels: documentation, patch

#573 Improve EPUB Reader: UI Enhancements (Line Height, Letter Spacing, Fl…
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookLoreUser.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/EpubViewerPreferences.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/EpubViewerPreferencesEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/user/DefaultUserSettingsProvider.java
  booklore-api/src/main/resources/db/migration/V34__Add_letter_spacing_and_line_height_for_epub_settings.sql
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.scss
  booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
  booklore-ui/src/app/book/components/epub-viewer/epub-reader-helper.ts
  booklore-ui/src/app/book/components/epub-viewer/epub-theme-util.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/settings/reader-preferences/cbx-reader-preferences-component/cbx-reader-preferences-component.html
  booklore-ui/src/app/settings/reader-preferences/cbx-reader-preferences-component/cbx-reader-preferences-component.scss
  booklore-ui/src/app/settings/reader-preferences/cbx-reader-preferences-component/cbx-reader-preferences-component.ts
  booklore-ui/src/app/settings/reader-preferences/epub-reader-preferences-component/epub-reader-preferences-component.html
  booklore-ui/src/app/settings/reader-preferences/epub-reader-preferences-component/epub-reader-preferences-component.scss
  booklore-ui/src/app/settings/reader-preferences/epub-reader-preferences-component/epub-reader-preferences-component.ts
  booklore-ui/src/app/settings/reader-preferences/pdf-reader-preferences-component/pdf-reader-preferences-component.html
  booklore-ui/src/app/settings/reader-preferences/pdf-reader-preferences-component/pdf-reader-preferences-component.scss
  booklore-ui/src/app/settings/reader-preferences/pdf-reader-preferences-component/pdf-reader-preferences-component.ts
  booklore-ui/src/app/settings/reader-preferences/reader-preferences-service.ts
  booklore-ui/src/app/settings/reader-preferences/reader-preferences.component.html
  booklore-ui/src/app/settings/reader-preferences/reader-preferences.component.ts
  booklore-ui/src/app/settings/user-management/user.service.ts
  booklore-ui/src/main.ts
Labels: feature

#589 Carify max upload size note to indicate restart is required
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
  booklore-ui/src/app/settings/metadata-settings-component/metadata-settings-component.html
Labels: documentation

#590 fix: clear selected books after assigning to a shelf
  booklore-ui/src/app/book/components/book-browser/book-browser.component.ts
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/settings/global-preferences/global-preferences.component.html
Labels: bug

#599 Allow metadata fields to be explicitly cleared
  booklore-api/src/main/java/com/adityachandel/booklore/controller/MetadataController.java
  booklore-api/src/main/java/com/adityachandel/booklore/mapper/MetadataClearFlagsMapper.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/MetadataClearFlags.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/MetadataUpdateWrapper.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/BookMetadata.java
  booklore-api/src/main/java/com/adityachandel/booklore/model/dto/request/BulkMetadataUpdateRequest.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataUpdater.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/backuprestore/BookMetadataRestorer.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/writer/EpubMetadataWriter.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/writer/MetadataCopyHelper.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/writer/MetadataWriter.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/writer/PdfMetadataWriter.java
  booklore-api/src/main/java/com/adityachandel/booklore/util/MetadataChangeDetector.java
  booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts
  booklore-ui/src/app/book/components/book-browser/book-filter/book-filter.component.ts
  booklore-ui/src/app/book/components/book-browser/filters/HeaderFilter.ts
  booklore-ui/src/app/book/components/book-browser/metadata-restore-dialog-component/metadata-restore-dialog-component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-editor/metadata-editor.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-picker/metadata-picker.component.ts
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-searcher/metadata-searcher.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
  booklore-ui/src/app/book/metadata/bulk-metadata-update-component/bulk-metadata-update-component.html
  booklore-ui/src/app/book/metadata/bulk-metadata-update-component/bulk-metadata-update-component.ts
  booklore-ui/src/app/book/model/book.model.ts
  booklore-ui/src/app/book/service/book.service.ts
Labels: feature

#601 Resolve data consistency and selection issues in PrimeNG p-table
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html
  booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts
Labels: bug

#605 Sync favicon color with primary theme
  booklore-ui/src/app/layout/component/theme-configurator/favicon-service.ts
  booklore-ui/src/app/layout/component/theme-configurator/theme-configurator.component.ts
Labels: feature

#607 Implement click-to-filter for series and publisher from book metadata
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.html
  booklore-ui/src/app/book/metadata/book-metadata-center/metadata-viewer/metadata-viewer.component.ts
Labels: feature

#631 Deleting books now cleans up empty directories left behind
  booklore-api/build.gradle
  booklore-api/src/main/java/com/adityachandel/booklore/model/entity/LibraryEntity.java
  booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
  booklore-api/src/test/java/com/adityachandel/booklore/BookServiceDeleteTests.java
Labels: feature
